### ISSUE TITLE
Is the demo working?

### ISSUE THREAD

**Issue by valerio-bozzolan** [astridx/LeafletControlRouteToAddress#1]
Hi all! I was trying the demo but I see this:

![Screenshot_2022_02_15_125356](https://user-images.githubusercontent.com/6052909/154057187-54c9264b-b030-4d40-81e0-447f09613d40.png)

Are you aware of that? :) Thank you so much!

**Comment by astridx** [comment]
Thank you . Your are right. I changed Content Security Policy and forgot this Demo.
Will think about how to solve this.

**Comment by bertvandepoel** [comment]
Just to let you know it's still not working for me. Did you manage to have a look yet? I first thought it was one of my privacy addons, but see CSP errors even with them disabled.

**Comment by astridx** [comment]
Thanks for informing me.
You can find a working example on this page: https://ergotherapie-kaisersesch.de/anfahrt
